[package]
name = "rodio"
version = "0.17.1"
license = "MIT OR Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/RustAudio/rodio"
documentation = "https://docs.rs/rodio"
exclude = ["assets/**", "tests/**"]
edition = "2021"

[dependencies]
<<<<<<< HEAD
cpal = "0.15"
||||||| parent of c361a5d (switch to fork for cpal)
cpal = "0.13"
=======
# cpal = "0.13"
cpal = { git = "https://github.com/alexmoon/cpal.git" }
>>>>>>> c361a5d (switch to fork for cpal)
claxon = { version = "0.4.2", optional = true }
hound = { version = "3.3.1", optional = true }
lewton = { version = "0.10", optional = true }
<<<<<<< HEAD
# minimp3_fixed = { version = "0.5.4", optional = true}
||||||| parent of c361a5d (switch to fork for cpal)
# minimp3 = { version = "0.5.0", optional = true }
=======
>>>>>>> c361a5d (switch to fork for cpal)
minimp3 = { git = "https://github.com/dskleingeld/minimp3-rs.git", optional = true }
<<<<<<< HEAD
symphonia = { version = "0.5.2", optional = true, default-features = false }
crossbeam-channel = { version = "0.5.8", optional = true }
||||||| parent of c361a5d (switch to fork for cpal)
# minimp3 = { path = "../minimp3-rs", optional = true }
=======
>>>>>>> c361a5d (switch to fork for cpal)

[features]
default = ["flac", "vorbis", "wav", "mp3"]

flac = ["claxon"]
vorbis = ["lewton"]
wav = ["hound"]
mp3 = ["symphonia-mp3"]
minimp3 = ["dep:minimp3_fixed"]
wasm-bindgen = ["cpal/wasm-bindgen"]
symphonia-aac = ["symphonia/aac"]
symphonia-all = ["symphonia-aac", "symphonia-flac", "symphonia-isomp4", "symphonia-mp3", "symphonia-vorbis", "symphonia-wav"]
symphonia-flac = ["symphonia/flac"]
symphonia-isomp4 = ["symphonia/isomp4"]
symphonia-mp3 = ["symphonia/mp3"]
symphonia-vorbis = ["symphonia/vorbis"]
symphonia-wav = ["symphonia/wav", "symphonia/pcm", "symphonia/adpcm"]

[dev-dependencies]
quickcheck = "0.9.2"

[[example]]
name = "music_m4a"
required-features = ["symphonia-isomp4", "symphonia-aac"]
